application: 7cerebros
version: 7
runtime: python
api_version: 1

handlers:

# Static resources

- url: /robots.txt
  static_files: assets/common/robots.txt
  upload: assets/common/robots.txt

- url: /favicon.ico
  static_files: assets/common/favicon.ico
  upload: assets/common/favicon.ico

- url: /images
  static_dir: assets/images

- url: /flash
  static_dir: assets/flash

- url: /css
  static_dir: assets/css

- url: /js
  static_dir: assets/js

# Web controllers

- url: /.*
  script: controller/main.py

